function createfigure_rt(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 21-Mar-2016 11:43:43

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',4,'FontWeight','bold',...
    'FontSize',26);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',6);
set(plot1(1),'DisplayName','Random','Color',[1 0 0]);
set(plot1(2),'DisplayName','JDC','Color',[0 0 1]);
set(plot1(3),'DisplayName','LTDF','Color',[0 1 0]);

% Create xlabel
xlabel({'Time (interval)'});

% Create ylabel
ylabel({'Delivery Debt'});

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.149783554041024 0.754728136403622 0.233766228966899 0.148936166091168]);

