%% Configuration File
% 21 links, deadline = 30 slots
N_runs = 1;
N_frames = 20000;
N_slots_per_frame = 50;
N_links = 21;
qmax = 0.9894;
rho = 0.995;
qn = qmax*rho*ones(N_links,1); 
channel_prob = 0.5*ones(N_links, 1);
arrival_type = 'Bernoulli'; % One, Uniform, Bernoulli
arrival_prob = 1*ones(N_links, 1);
weight_mode = 'log';
arrival_per_frame_max = 3*ones(N_links, 1);
beta = 0;
%policy = 'LDF';
policy = 'decentralized';
gamma = 50;
N_swap = 5;
heavy_ball = 1;